---
swagger: "2.0"
info:
  description: "KomMonitor Client config file storage server API, which can store\
    \ and serve various config files for Kommonitor client(s)."
  version: "0.0.1"
  title: "KomMonitor Client Config Storage Server API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "christian.danowski-buhren@hs-bochum.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8088"
basePath: "/config"
tags:
- name: "web-client app config"
  description: "Config for Web Client application configuration"
- name: "web-client keycloak config"
  description: "Config for Web Client Keycloak configuration"
- name: "web-client controls config"
  description: "Config for Web Client controls configuration"
schemes:
- "http"
- "https"
security:
- basicAuth: []
paths:
  /client-app-config:
    get:
      tags:
      - "web-client app config"
      summary: "retrieve web app client config."
      description: "retrieve web app client config."
      operationId: "getWebAppConfig"
      produces:
      - "application/javascript"
      parameters: []
      responses:
        "200":
          description: "The web app config file as JavaScript file."
          schema:
            type: "file"
      x-swagger-router-controller: "WebClientAppConfig"
    post:
      tags:
      - "web-client app config"
      summary: "Send web app client config to be stored on server."
      description: "Send web app client config to be stored on server."
      operationId: "postWebAppConfig"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "appConfig"
        in: "formData"
        description: "The file to upload as javascript file."
        required: false
        type: "file"
      responses:
        "200":
          description: "OK"
        "500":
          description: "Error"
      x-swagger-router-controller: "WebClientAppConfig"
  /client-keycloak-config:
    get:
      tags:
      - "web-client keycloak config"
      summary: "retrieve web app client keycloak config."
      description: "retrieve web app client keycloak config."
      operationId: "getWebAppKeycloakConfig"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "The web app keycloak config file as JSON file."
          schema:
            type: "file"
      x-swagger-router-controller: "WebClientKeycloakConfig"
    post:
      tags:
      - "web-client keycloak config"
      summary: "Send web app client keycloak config to be stored on server."
      description: "Send web app client keycloak config to be stored on server."
      operationId: "postWebAppKeycloakConfig"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "appConfig"
        in: "formData"
        description: "The file to upload as JSON file."
        required: false
        type: "file"
      responses:
        "200":
          description: "OK"
        "500":
          description: "Error"
      x-swagger-router-controller: "WebClientKeycloakConfig"
  /client-controls-config:
    get:
      tags:
      - "web-client controls config"
      summary: "retrieve web app client controls config."
      description: "retrieve web app client controls config."
      operationId: "getWebAppControlsConfig"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "The web app controls config file as JSON file."
          schema:
            type: "file"
      x-swagger-router-controller: "WebClientControlsConfig"
    post:
      tags:
      - "web-client controls config"
      summary: "Send web app client controls config to be stored on server."
      description: "Send web app client controls config to be stored on server."
      operationId: "postWebAppControlsConfig"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "appConfig"
        in: "formData"
        description: "The file to upload as JSON file."
        required: false
        type: "file"
      responses:
        "200":
          description: "OK"
        "500":
          description: "Error"
      x-swagger-router-controller: "WebClientControlsConfig"
securityDefinitions:
  basicAuth:
    type: "basic"
definitions: {}
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
